In [1]:
import pandas as pd

In [2]:
st = pd.read_csv("sampleSuperstore.csv")
st.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [3]:
st["Sales"].dtypes

dtype('float64')

In [4]:
st.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           1
Quantity        0
Discount        0
Profit          0
dtype: int64

In [5]:
st.notna()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,True,True,True,True,True,True,True,True,True,True,True,True,True
9990,True,True,True,True,True,True,True,True,True,True,True,True,True
9991,True,True,True,True,True,True,True,True,True,True,True,True,True
9992,True,True,True,True,True,True,True,True,True,True,True,True,True
9993,True,True,True,True,True,True,True,True,True,True,True,True,True

In [6]:
# st.dropna()
empty_row = st.dropna(subset = ["Sales"])
print(empty_row)

           Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky
1       Second Class   Consumer  United States        Henderson    Kentucky
2       Second Class  Corporate  United States      Los Angeles  California
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida
...              ...        ...            ...              ...         ...
9989    Second Class   Consumer  United States            Miami     Florida
9990  Standard Class   Consumer  United States       Costa Mesa  California
9991  Standard Class   Consumer  United States       Costa Mesa  California
9992  Standard Class   Consumer  United States       Costa Mesa  California
9993    Second Class   Consumer  United States      Westminster  California

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0           42420  South        Furniture    Bookcases  261.9600         2
1           42420  South        Furniture       Chairs  731.9400         3
2           90036   West  Office Supplies       Labels   14.6200         2
3           33311  South        Furniture       Tables  957.5775         5
4           33311  South  Office Supplies      Storage   22.3680         2
...           ...    ...              ...          ...       ...       ...
9989        33180  South        Furniture  Furnishings   25.2480         3
9990        92627   West        Furniture  Furnishings   91.9600         2
9991        92627   West       Technology       Phones  258.5760         2
9992        92627   West  Office Supplies        Paper   29.6000         4
9993        92683   West  Office Supplies   Appliances  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9993 rows x 13 columns]

In [7]:
st.head(15)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
5,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
6,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800,4,0.00,1.9656
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520,6,0.20,90.7152
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040,3,0.20,5.7825
9,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000,5,0.00,34.4700
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.1840,9,0.20,85.3092
11,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,911.4240,4,0.20,68.3568
12,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,NaN,3,0.20,5.4432
13,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,407.9760,3,0.20,132.5922
14,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,68.8100,5,0.80,-123.8580

In [8]:
print("total rows before cleaning", st.shape[0])

total rows before cleaning 9994

In [9]:
st.duplicated().sum()

np.int64(17)

In [10]:
st.drop_duplicates(inplace = True)

In [11]:
st.duplicated().sum()

np.int64(0)

In [12]:
print("total_rows after cleaning", st.shape[0])

total_rows after cleaning 9977

In [13]:
duplicate_rows = st[st.duplicated()]
print(duplicate_rows.head())

Empty DataFrame
Columns: [Ship Mode, Segment, Country, City, State, Postal Code, Region, Category, Sub-Category, Sales, Quantity, Discount, Profit]
Index: []

In [14]:
Region_sales = st.groupby("Region")["Sales"].sum()
print("high sales in the",Region_sales)

Region_low_sales = st.groupby("Region")["Sales"].sum().sort_values().head(2)
print("low sales in the ",Region_low_sales)

high sales in the Region
Central    500782.8528
East       678435.1960
South      391706.3530
West       725255.6365
Name: Sales, dtype: float64
low sales in the  Region
South      391706.3530
Central    500782.8528
Name: Sales, dtype: float64

In [15]:
State_high_sales = st.groupby("State")["Sales"].sum().head(5).sort_values(ascending = True)
print("High sales in the", State_high_sales)

State_low_sales = st.groupby("State")["Sales"].sum().head(3).sort_values(ascending = True)
print("low sales in the", State_low_sales)

High sales in the State
Arkansas       11678.1300
Alabama        19510.6400
Colorado       32108.1180
Arizona        35282.0010
California    457576.2715
Name: Sales, dtype: float64
low sales in the State
Arkansas    11678.130
Alabama     19510.640
Arizona     35282.001
Name: Sales, dtype: float64

In [16]:
category_sales = st.groupby("Category")["Sales"].sum().head().sort_values(ascending=False)
print(category_sales)

Category
Technology         836154.0330
Furniture          741306.3133
Office Supplies    718719.6920
Name: Sales, dtype: float64

In [17]:
top_10_product = st.groupby("Sub-Category")["Sales"].sum().head(5).sort_values(ascending = False)
print(top_10_product)

Sub-Category
Binders        203409.1690
Accessories    167380.3180
Bookcases      114879.9963
Appliances     107532.1610
Art             27107.0320
Name: Sales, dtype: float64

In [18]:
correlation = st["Discount"].corr(st["Profit"])
print("Due to discount we come profit or loss", correlation)

Due to discount we come profit or loss -0.21966206449082398

In [19]:
shipping_analysis = st.groupby(["Ship Mode", "Region"]).size().unstack()
print(shipping_analysis)

Region          Central  East  South  West
Ship Mode
First Class         298   490    234   515
Same Day            120   155     83   184
Second Class        464   530    329   620
Standard Class     1437  1670    974  1874

In [20]:
st.info()

<class 'pandas.DataFrame'>
Index: 9977 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9977 non-null   str
 1   Segment       9977 non-null   str
 2   Country       9977 non-null   str
 3   City          9977 non-null   str
 4   State         9977 non-null   str
 5   Postal Code   9977 non-null   int64
 6   Region        9977 non-null   str
 7   Category      9977 non-null   str
 8   Sub-Category  9977 non-null   str
 9   Sales         9976 non-null   float64
 10  Quantity      9977 non-null   int64
 11  Discount      9977 non-null   float64
 12  Profit        9977 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 1.1 MB

In [21]:
st["Sales"] = st["Sales"].fillna(0)
print(st["Sales"])

0       261.9600
1       731.9400
2        14.6200
3       957.5775
4        22.3680
          ...
9989     25.2480
9990     91.9600
9991    258.5760
9992     29.6000
9993    243.1600
Name: Sales, Length: 9977, dtype: float64

In [22]:
st.info()

<class 'pandas.DataFrame'>
Index: 9977 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9977 non-null   str
 1   Segment       9977 non-null   str
 2   Country       9977 non-null   str
 3   City          9977 non-null   str
 4   State         9977 non-null   str
 5   Postal Code   9977 non-null   int64
 6   Region        9977 non-null   str
 7   Category      9977 non-null   str
 8   Sub-Category  9977 non-null   str
 9   Sales         9977 non-null   float64
 10  Quantity      9977 non-null   int64
 11  Discount      9977 non-null   float64
 12  Profit        9977 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 1.1 MB

In [25]:
st.to_csv("Clean_superstore_data.csv", index=False)
print("File successfully saved")

File successfully saved